sudo: false
language: ruby
branches:
  only:
  - master
cache: bundler
before_script:
- git config --global user.name "crystal"
- git config --global user.email "crystal@legenddigital.cn"
- git clone https://${GH_TOKEN}@${GH_REF} -b gh-pages --depth=1 build
script:
- bundle exec middleman build --clean
after_script:
- cd ./build
- git add .
- git commit -m "update page automatically"
- git push
env:
  global:
   - GH_REF: github.com/coinwapi/docs.git
   - secure: QKm2WmU1I1fVCldlh0DFJfOkOMGMTa2j2otsDM15yqnmlra830YbIdJuNpG87HhsVhvuN6R0lIaz/jpXHMY69ytXHHpe5CeL16dexou1eGg+r7FyXl5OmnMAvhSaXI2K4j96WSkh6KVaDx1n5YuGI5AW5deVyTRagaSg8+N+gpb5D5Mn7hM+MMZ27Eece9+iVXsPhEzOReEVR6DMyBwQagwLY/F4ylD7jqsTNeDHnOBC2OOQj53P2W87Hxd99GU0LaAUTVN/BUbo4ze5ouwjHOSSb+k6u48v5dU7FmeLSER9YYEAw6o1yfbbphterteqX9Xyln4YlRvooV9ytQ2LGYBZSZsIC/QZPW3FTWbLn/n8TaJ19mPYZMapAPS4JFEeCPKK2JS6KqSgQQQ1UpyP4OJioHr1mj9PrD5FfHkZ0pZFHL7Ffp3U2BSrrWShOLNU7kROA5jpWf2/C9ujGWiqeDwSJI68oneIMLN+aVlRzqgExBN+vUQqB0GL5d+OktQFF2T5E6CU1Ay5tHMUaD1HKq88DVMjI/AapBPwYRD7f9H262CAqEUlXN/QSl57/eXn0AGCjmUFCeMYnmbRhfUnricraS+CzToqEdNu0DwRDiREMVLSb615dUb3rYuOOru7eW2w+nPAFRVE6L8vqhkBPM84t9BOHBsX4WiW4gmrW5s=
